const data = {
  products: [
    {
      _id: "1",
      name: "Pattern Shape Bedding",
      category: "Beddings",
      image: "/images/p1.jpg",
      price: 120,
      brand: "George",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Pink Bedding",
      category: "Beddings",
      image: "/images/p2.jpg",
      price: 200,
      brand: "Fendi",
      rating: 4.5,
      numReviews: 12,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Pink Flower Bedding",
      category: "Beddings",
      image: "/images/p3.jpg",
      price: 220,
      brand: "Louis V",
      rating: 4.5,
      numReviews: 16,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Grey Bedding",
      category: "Beddings",
      image: "/images/p4.jpg",
      price: 100,
      brand: "George",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Grey Pattern Shape Bedding",
      category: "Beddings",
      image: "/images/p5.jpg",
      price: 160,
      brand: "George",
      rating: 4.5,
      numReviews: 13,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Bumblebee Bedding",
      category: "Beddings",
      image: "/images/p6.jpg",
      price: 320,
      brand: "CK",
      rating: 4.5,
      numReviews: 20,
      description: "high quality product",
    },
  ],
};
export default data;
